//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMLGen.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class PathConfigurationSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PathConfigurationSettings defaultInstance = ((PathConfigurationSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PathConfigurationSettings())));
        
        public static PathConfigurationSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DidFirstLoad {
            get {
                return ((bool)(this["DidFirstLoad"]));
            }
            set {
                this["DidFirstLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UnpackedDataDirectory {
            get {
                return ((string)(this["UnpackedDataDirectory"]));
            }
            set {
                this["UnpackedDataDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameDataDirectory {
            get {
                return ((string)(this["GameDataDirectory"]));
            }
            set {
                this["GameDataDirectory"] = value;
            }
        }
    }
}
